// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf-TDfh4xERFOcsmcyJgAv46jxrUYrAK0',
    appId: '1:791500667716:web:4fc42017dda04e5f5f7511',
    messagingSenderId: '791500667716',
    projectId: 'educ8-778c9',
    authDomain: 'educ8-778c9.firebaseapp.com',
    storageBucket: 'educ8-778c9.appspot.com',
    measurementId: 'G-HVZSXR5J95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx4W5qIN0UEwGGNQZxPO4Sm7enZcN49M8',
    appId: '1:791500667716:android:7ac564d507cdd8c35f7511',
    messagingSenderId: '791500667716',
    projectId: 'educ8-778c9',
    storageBucket: 'educ8-778c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYM6SpeRaDel3aAdeIVOvsUN_IMKaiS-I',
    appId: '1:791500667716:ios:103ad55e90e060105f7511',
    messagingSenderId: '791500667716',
    projectId: 'educ8-778c9',
    storageBucket: 'educ8-778c9.appspot.com',
    iosBundleId: 'com.example.educ8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYM6SpeRaDel3aAdeIVOvsUN_IMKaiS-I',
    appId: '1:791500667716:ios:0cd97c6c98d6b96c5f7511',
    messagingSenderId: '791500667716',
    projectId: 'educ8-778c9',
    storageBucket: 'educ8-778c9.appspot.com',
    iosBundleId: 'com.example.educ8.RunnerTests',
  );
}
